[Service]
  Host = "192.168.1.64"
  Port = 49997
  ConnectRetries = 3
  Labels = []
  OpenMsg = "device opcua golang started"
  Timeout = 5000
  EnableAsyncReadings = true
  AsyncBufferSize = 16

[Registry]
  Host = "localhost"
  Port = 8500
  CheckInterval = "10s"
  FailLimit = 3
  FailWaitTime = 10
  Type = "consul"

[Clients]
  [Clients.Data]
    Name = "edgex-core-data"
    Protocol = "http"
    Host = "localhost"
    Port = 48080
    Timeout = 5000

  [Clients.Metadata]
    Name = "edgex-core-metadata"
    Protocol = "http"
    Host = "localhost"
    Port = 48081
    Timeout = 5000

  [Clients.Logging]
    Name = "edgex-support-logging"
    Protocol = "http"
    Host = "localhost"
    Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 12800
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Logging]
  EnableRemote = false
  File = "./device-opcua-go.log"

[Writable]
  LogLevel = "INFO"

# Pre-define Devices
[[DeviceList]]
  Name = "SimulationServer"
  Profile = "OPCUA-Server"
  Description = "OPCUA device is created for test purpose"
  Labels = [ "test" ]
  [DeviceList.Protocols]
      [DeviceList.Protocols.opcua]
          Endpoint = "opc.tcp://192.168.1.82:53530/OPCUA/SimulationServer"

# Subscription configs
[Driver]
  SubscribeJson = " {\"devices\":[{\"deviceName\":\"SimulationServer\",\"nodeIds\":[\"ns=3;i=1001\",\"ns=3;i=1002\"],\"policy\":\"None\",\"mode\":\"None\",\"certFile\":\"\",\"keyFile\":\"\"}]} "
