[Writable]
LogLevel = 'INFO'
    [Writable.StoreAndForward]
    Enabled = false
    RetryInterval = '5m'
    MaxRetryCount = 10

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48530
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is a MQTT Export Application Service'
Timeout = '30s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/app-service-metadata.log'

[Database]
Type = "mongodb"
Host = "localhost"
Port = 27017
Timeout = "30s"
Username = ""
Password = ""

# [SecretStore]
#   Host = 'localhost'
#   Port = 8200
#   Path = '/v1/secret/edgex/appservice/'
#   Protocol = 'https'

#   [SecretStore.Authentication]
#   AuthType = 'X-Vault-Token'
#   AuthToken = 'edgex'

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "localhost"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5580
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

# Choose either an HTTP trigger or MessageBus trigger (aka Binding)

#[Binding]
#Type="http"

[Binding]
Type="messagebus"
SubscribeTopic="events"
PublishTopic="filteredevents"

[ApplicationSettings]
GatewayId = "ElectricPlant"
GatewayDescription = "description"
GatewayHostname = "localhost"
GatewayRouter = "localhost"
GatewayRouterPort = "22"
GatewayDeployNetwork = "edgex-network"
GatewayLatitude = "36.0"
GatewayLongitude = "-98.0"
GatewayAccessToken = "changeme"
GatewayUsername = "changeme"
GatewayPlatform = "changeme"
DeviceNames = "versicharge-0001"
MqttProtocol = "tcp"
MqttHostname = ""
MqttPort = "443"
MqttPublisher = "EdgexExport"
MqttUser = "mqtt_admin"
MqttPassword = "mqtt_admin"
MqttTrustStore = ""
MqttTopic = "EdgexGatewayData"
MetadataClient = "http://localhost:48081"
MetadataPublishIntervalSecs = "30"

