version: '3.7'
networks:
  edgex-network:
    driver: bridge
services:
  edgex-core-consul:
    command: agent -ui -bootstrap -server -client 0.0.0.0
    image: consul:${CONSUL_VERSION}
    networks:
      edgex-network: {}
    ports:
      - 8500:8500/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root:root
    volumes:
      - consul-config:/consul/config:z
      - consul-data:/consul/data:z
  edgex-redis:
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      REGISTRY_HOST: edgex-core-consul
    image: redis:${REDIS_VERSION}
    networks:
      edgex-network: {}
    ports:
      - 6379:6379/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root:root
    volumes:
      - db-data:/data:z
  edgex-core-metadata:
    container_name: edgex-core-metadata
    depends_on:
    - edgex-core-consul
    - edgex-redis
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      NOTIFICATIONS_SENDER: edgex-core-metadata
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-core-metadata
    image: edgexfoundry/core-metadata-arm64:${EDGEX_FOUNDRY_VERSION}
    networks:
      edgex-network: {}
    ports:
      - 127.0.0.1:59881:59881/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
  edgex-mqtt-broker:
    command: /usr/sbin/mosquitto -c /mosquitto-no-auth.conf
    image: eclipse-mosquitto:${ECLIPSE_MOSQUITTO_VERSION}
    networks:
      edgex-network: {}
    ports:
    - published: 1883
      target: 1883
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
  edgex-core-command:
    container_name: edgex-core-command
    depends_on:
    - edgex-core-consul
    - edgex-redis
    - edgex-core-metadata
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-core-command
    hostname: edgex-core-command
    image: edgexfoundry/core-command-arm64:${EDGEX_FOUNDRY_VERSION}
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:59882:59882/tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001

  edgex-core-data:
    container_name: edgex-core-data
    depends_on:
    - edgex-core-consul
    - edgex-redis
    - edgex-core-metadata
    - edgex-mqtt-broker
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_AUTHMODE: none
      MESSAGEQUEUE_HOST: edgex-mqtt-broker
      MESSAGEQUEUE_OPTIONAL_CLIENTID: core-data
      MESSAGEQUEUE_PORT: 1883
      MESSAGEQUEUE_PROTOCOL: tcp
      MESSAGEQUEUE_TYPE: mqtt
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-core-data
    hostname: edgex-core-data
    image: edgexfoundry/core-data-arm64:${EDGEX_FOUNDRY_VERSION}
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:5563:5563/tcp
    - 127.0.0.1:59880:59880/tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001



# **************
# AIR Components
# **************
  service-metadata:
    container_name: air-app-service-metadata
    depends_on:
    - edgex-core-consul
    - edgex-core-data
    - edgex-core-metadata
    - edgex-mqtt-broker
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      DATABASES_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: air-app-service-metadata
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_AUTHMODE: none
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_CLIENTID: airmetadata
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-mqtt-broker
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_PORT: 1883
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_PROTOCOL: tcp
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-mqtt-broker
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_PORT: 1883
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_PROTOCOL: tcp
      TRIGGER_EDGEXMESSAGEBUS_TYPE: mqtt
      WRITABLE_LOGLEVEL: DEBUG
      APPLICATIONSETTINGS_MQTTHOSTNAME: ${AIR_MQTT_HOSTNAME}
      APPLICATIONSETTINGS_MQTTPORT: ${AIR_MQTT_PORT}
      APPLICATIONSETTINGS_MQTTUSER: ${AIR_MQTT_USER}
      APPLICATIONSETTINGS_MQTTPASSWORD: ${AIR_MQTT_PASSWORD}
      APPLICATIONSETTINGS_MQTTTOPIC: ${AIR_MQTT_DATA_TOPIC}
      APPLICATIONSETTINGS_MQTTPUBLISHER: ${AIR_MQTT_DATA_METADATA_PUBLISHER}
      APPLICATIONSETTINGS_GATEWAYID: ${GATEWAY_ID}
      APPLICATIONSETTINGS_GATEWAYDESCRIPTION: ${GATEWAY_DESCRIPTION}
      APPLICATIONSETTINGS_GATEWAYHOSTNAME: ${GATEWAY_HOSTNAME}
      APPLICATIONSETTINGS_GATEWAYROUTER: ${GATEWAY_ROUTER}
      APPLICATIONSETTINGS_GATEWAYROUTERPORT: ${GATEWAY_ROUTER_PORT}
      APPLICATIONSETTINGS_GATEWAYDEPLOYNETWORK: ${GATEWAY_DEPLOY_NETWORK}
      APPLICATIONSETTINGS_GATEWAYLATITUDE: ${GATEWAY_LATITUDE}
      APPLICATIONSETTINGS_GATEWAYLONGITUDE: ${GATEWAY_LONGITUDE}
      APPLICATIONSETTINGS_GATEWAYACCESSTOKEN: ${GATEWAY_ACCESS_TOKEN}
      APPLICATIONSETTINGS_GATEWAYUSERNAME: ${GATEWAY_USERNAME}
      APPLICATIONSETTINGS_GATEWAYPLATFORM: ${GATEWAY_PLATFORM}
      APPLICATIONSETTINGS_METADATAPUBLISHINTERVALSECS: ${GATEWAY_METADATA_PUBLISH_INTERVAL_SECS}
    hostname: air-app-service-metadata
    image: public.ecr.aws/tibcolabs/labs-air-edgex-app-service-metadata-arm64:${LABS_AIR_VERSION}
    networks:
      edgex-network: {}
    ports:
      - 127.0.0.1:48535:48535/tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    
  device-generic-rest:
    container_name: air-device-generic-rest
    depends_on:
    - edgex-core-consul
    - edgex-core-data
    - edgex-core-metadata
    - edgex-mqtt-broker
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_AUTHMODE: none
      MESSAGEQUEUE_HOST: edgex-mqtt-broker
      MESSAGEQUEUE_PORT: 1883
      MESSAGEQUEUE_PROTOCOL: tcp
      MESSAGEQUEUE_TYPE: mqtt
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: air-device-generic-rest
      WRITABLE_LOGLEVEL: DEBUG
    hostname: air-device-generic-rest
    image: public.ecr.aws/tibcolabs/labs-air-edgex-device-generic-rest-arm64:${LABS_AIR_VERSION}
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:49565:49565/tcp
    read_only: true
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
  
  device-esp32-mqtt:
    container_name: air-device-esp32-mqtt
    depends_on:
    - edgex-core-consul
    - edgex-core-data
    - edgex-core-metadata
    - edgex-mqtt-broker
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_TYPE: mqtt
      MESSAGEQUEUE_PROTOCOL: tcp
      MESSAGEQUEUE_HOST: edgex-mqtt-broker
      MESSAGEQUEUE_PORT: 1883
      MESSAGEQUEUE_AUTHMODE: none
      MESSAGEQUEUE_OPTIONAL_CLIENTID: device-esp32-mqtt
      MQTTBROKERINFO_HOST: ${AIR_MQTT_HOSTNAME}
      MQTTBROKERINFO_PORT: ${AIR_MQTT_PORT}
      MQTTBROKERINFO_CLIENTID: ${AIR_MQTT_ESP32_CLIENTID}
      MQTTBROKERINFO_AUTHMODE: usernamepassword
      MQTTBROKERINFO_USERNAME: ${AIR_MQTT_USER}
      MQTTBROKERINFO_PASSWORD: ${AIR_MQTT_PASSWORD}
      MQTTBROKERINFO_INCOMINGTOPIC: ${AIR_MQTT_ESP32_INCOMINGTOPIC}
      MQTTBROKERINFO_RESPONSETOPIC: ${AIR_MQTT_ESP32_RESPONSETOPIC}
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: air-device-esp32-mqtt
      WRITABLE_LOGLEVEL: DEBUG
    hostname: air-device-esp32-mqtt
    image: public.ecr.aws/tibcolabs/labs-air-edgex-device-esp32-mqtt-arm64:${LABS_AIR_VERSION}
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:49560:49560/tcp
    read_only: true
    security_opt:
    - no-new-privileges:true
    user: 2002:2001


volumes:
  consul-config: {}
  consul-data: {}
  db-data: {}
  kuiper-data: {}

