[Service]
Host = "labsair-device-enersys-mqtt"
Port = 49985
ConnectRetries = 3
Labels = []
OpenMsg = "device enersys started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "/res"

[Logging]
EnableRemote = true
File = "./device-mqtt.log"

[Writable]
LogLevel = "INFO"

# Pre-define Devices
[[DeviceList]]
  Name = "aaaaaaaaaa17"
  Profile = "Enersys-Device"
  Description = "Enersys device"
  Labels = [ "industrial", "mqtt" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
      Schema = "tcp"
      Host = "192.168.1.92"
      Port = "1883"
      ClientId = "EnersysCommandPublisher"
      User = "mqtt_admin"
      Password = "mqtt_admin"
      Topic = "CommandListenerTopic_aaaaaaaaaa17"

# Driver configs
[Driver]
IncomingSchema = "tcp"
IncomingHost = "192.168.1.92"
IncomingPort = "1883"
IncomingUser = "mqtt_admin"
IncomingPassword = "mqtt_admin"
IncomingQos = "0"
IncomingKeepAlive = "3600"
IncomingClientId = "EnersysIncomingDataSubscriber"
IncomingTopic = "EnersysData"
ResponseSchema = "tcp"
ResponseHost = "192.168.1.92"
ResponsePort = "1883"
ResponseUser = "mqtt_admin"
ResponsePassword = "mqtt_admin"
ResponseQos = "0"
ResponseKeepAlive = "3600"
ResponseClientId = "EnersysCommandResponseSubscriber"
ResponseTopic = "EnersysResponse"
