[Writable]
LogLevel = 'INFO'

[Service]
Host = "labsair-device-siemens-rest"
Port = 59998
ConnectRetries = 20
Labels = []
OpenMsg = "Siemens REST device started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
Type = "consul"
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "/res"

# Driver configs
[Driver]

[Logging]
EnableRemote = true

# Pre-define Devices
[[DeviceList]]
  Name = "level2c"
  Profile = "Siemens-Device"
  Description = "Siemens VersiCharge RESTful Device that sends JSON data"
  Labels = [ "rest", "json" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]

