version: '3.7'
networks:
  edgex-network:
    driver: bridge
services:
  device-esp32-mqtt:
    container_name: air-device-esp32-mqtt
    depends_on:
    - edgex-core-consul
    - edgex-core-data
    - edgex-core-metadata
    - edgex-mqtt-broker
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_TYPE: mqtt
      MESSAGEQUEUE_PROTOCOL: tcp
      MESSAGEQUEUE_HOST: edgex-mqtt-broker
      MESSAGEQUEUE_PORT: 1883
      MESSAGEQUEUE_AUTHMODE: none
      MESSAGEQUEUE_OPTIONAL_CLIENTID: device-esp32-mqtt
      MQTTBROKERINFO_HOST: ${ADAPTER_MQTTBROKERINFO_HOST}
      MQTTBROKERINFO_PORT: ${ADAPTER_MQTTBROKERINFO_PORT}
      MQTTBROKERINFO_CLIENTID: ESP32MQTTClient
      MQTTBROKERINFO_AUTHMODE: ${ADAPTER_MQTTBROKERINFO_AUTHMODE}
      MQTTBROKERINFO_USERNAME: ${ADAPTER_MQTTBROKERINFO_USERNAME}
      MQTTBROKERINFO_PASSWORD: ${ADAPTER_MQTTBROKERINFO_PASSWORD}
      MQTTBROKERINFO_INCOMINGTOPIC: Trolleys/trolley
      MQTTBROKERINFO_RESPONSETOPIC: Troleys/response
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: air-device-esp32-mqtt
      WRITABLE_LOGLEVEL: DEBUG
    hostname: air-device-esp32-mqtt
    image: public.ecr.aws/tibcolabs/labs-air-edgex-device-esp32-mqtt${ARCH}:${LABS_AIR_VERSION}
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:49560:49560/tcp
    read_only: true
    security_opt:
    - no-new-privileges:true
    user: 2002:2001


