[Service]
Host = "labsair-device-labmonitor-simulator"
Port = 48998
ConnectRetries = 3
Labels = []
OpenMsg = "device LabMonitor started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "/res"

[Logging]
EnableRemote = true
File = "./device-labmonitor.log"

[Writable]
LogLevel = "INFO"

# Pre-define Devices
[[DeviceList]]
  Name = "smartvalve-0001"
  Profile = "LabMonitor-SimDevice"
  Description = "LabMonitor device simulator"
  Labels = [ "charger", "ev" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "devicelabmonitor"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "5s"
    OnChange = false
    Resource = "Temperature"
  [[DeviceList.AutoEvents]]
    Frequency = "5s"
    OnChange = false
    Resource = "Voltage"
  [[DeviceList.AutoEvents]]
    Frequency = "5s"
    OnChange = false
    Resource = "Amperage"

