[[DeviceList]]
  Name = "VADevice"
  ProfileName = "VideoAnalytics-MQTT-Device"
  Description = "MQTT device is created for video analytics purpose"
  Labels = [ "MQTT" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       # Comment out/remove below to use multi-level topics
       # CommandTopic = "CommandTopic"
       # Uncomment below to use multi-level topics
       CommandTopic = "command/VADevice"
#    [[DeviceList.AutoEvents]]
#       Interval = "20s"
#       OnChange = false
#       SourceName = "testrandfloat32"