networks:
  air-backend_air-network:
    name: edgex_edgex-network
    driver: bridge
services:
  service-metadata:
    container_name: air-app-service-metadata
    depends_on:
      consul:
        condition: service_started
      data:
        condition: service_started
      metadata:
        condition: service_started
      mqtt-broker:
        condition: service_started
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      DATABASES_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: air-app-service-metadata
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_AUTHMODE: none
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_CLIENTID: airmetadata
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-mqtt-broker
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_PORT: 1883
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_PROTOCOL: tcp
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-mqtt-broker
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_PORT: 1883
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_PROTOCOL: tcp
      TRIGGER_EDGEXMESSAGEBUS_TYPE: mqtt
      WRITABLE_LOGLEVEL: DEBUG
      APPLICATIONSETTINGS_MQTTHOSTNAME: ${AIR_MQTT_HOSTNAME}
      APPLICATIONSETTINGS_MQTTPORT: ${AIR_MQTT_PORT}
      APPLICATIONSETTINGS_MQTTUSER: ${AIR_MQTT_USER}
      APPLICATIONSETTINGS_MQTTPASSWORD: ${AIR_MQTT_PASSWORD}
      APPLICATIONSETTINGS_MQTTTOPIC: ${AIR_MQTT_DATA_TOPIC}
      APPLICATIONSETTINGS_MQTTPUBLISHER: ${AIR_MQTT_DATA_METADATA_PUBLISHER}
      APPLICATIONSETTINGS_GATEWAYID: ${GATEWAY_ID}
      APPLICATIONSETTINGS_GATEWAYDESCRIPTION: ${GATEWAY_DESCRIPTION}
      APPLICATIONSETTINGS_GATEWAYHOSTNAME: ${GATEWAY_HOSTNAME}
      APPLICATIONSETTINGS_GATEWAYROUTER: ${GATEWAY_ROUTER}
      APPLICATIONSETTINGS_GATEWAYROUTERPORT: ${GATEWAY_ROUTER_PORT}
      APPLICATIONSETTINGS_GATEWAYDEPLOYNETWORK: ${GATEWAY_DEPLOY_NETWORK}
      APPLICATIONSETTINGS_GATEWAYLATITUDE: ${GATEWAY_LATITUDE}
      APPLICATIONSETTINGS_GATEWAYLONGITUDE: ${GATEWAY_LONGITUDE}
      APPLICATIONSETTINGS_GATEWAYACCESSTOKEN: ${GATEWAY_ACCESS_TOKEN}
      APPLICATIONSETTINGS_GATEWAYUSERNAME: ${GATEWAY_USERNAME}
      APPLICATIONSETTINGS_GATEWAYPLATFORM: ${GATEWAY_PLATFORM}
      APPLICATIONSETTINGS_METADATAPUBLISHINTERVALSECS: ${GATEWAY_METADATA_PUBLISH_INTERVAL_SECS}
    hostname: air-app-service-metadata
    # image: public.ecr.aws/tibcolabs/labs-air-edgex-app-service-metadata:${LABS_AIR_VERSION}
    image: tibcosoftware/labs-air-edgex-app-service-metadata:2.2.0
    networks:
      air-backend_air-network: {}
    ports:
      - 127.0.0.1:48535:48535/tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001

version: '3.7'
volumes:
  consul-config: {}
  consul-data: {}
  db-data: {}
  kuiper-data: {}

